### ISSUE TITLE
Mal conteo de confirmados

### ISSUE THREAD

**Issue by durancristhian** [ManRueda/burgerjs-cli#13]
No se están teniendo en cuenta a los invitados para el conteo final de gente confirmada como asistente

<img width="719" alt="screen shot 2017-08-30 at 17 34 29" src="https://user-images.githubusercontent.com/4248944/29893786-9941abc2-8da9-11e7-9f1d-a678bfed2a22.png">

<img width="828" alt="screen shot 2017-08-30 at 17 34 42" src="https://user-images.githubusercontent.com/4248944/29893808-aae60ada-8da9-11e7-8318-950b92fca344.png">

**Comment by manrueda** [comment]
Ready. Para que después no anden diciendo cosas, como gato :wink:
